### ISSUE TITLE
exhaustive list of "towns/cities" in montgomery county

### ISSUE THREAD

**Issue by MareoRaft** [CodeforNRV/dog-registration#1]
When a person inputs their address, there will be a dropdown for the "city" field.  So I need a list of all the towns.  I found this on wikipedia:

# Communities
## Towns
Blacksburg
Christiansburg
Radford
## Census-designated places
Belview
Elliston
Lafayette
Merrimac
Plum Creek
Prices Fork
Riner
Shawsville
## Other unincorporated communities
Alleghany Springs
Bradshaw
Belmont
Childress
Ellett
Graysontown
Ironto
Long Shop
Lusters Gate
McCoy
McDonalds Mill
Pilot
Rogers
Sowers
Sugar Grove
Toms Creek
Vicker
Walton
Yellow Sulphur Springs

So now the question is which of these categories should i be using?  All three?  Just the first two?

**Comment by nealf** [comment]
That's a good question! I wasn't entirely sure which towns/areas were used by USPS for addressing, so I did a quick poking around and found this [map](https://www.zipmap.net/Virginia/Montgomery_County.htm) with zip codes for the county. Then I just used the [USPS lookup](https://tools.usps.com/zip-code-lookup.htm?citybyzipcode) to find what they correspond to:

- Blacksburg - 24060
- Christiansburg - 24073
- Radford - 24141
- Fairlawn - 24141
- Riner - 24149
- Pilot - 24138
- Shawsville - 24162
- Elliston - 24087
- Ironto - 24087
- Lafayette - 24087
- Catawba - 24070
- Hiwassee - 24347
- Newport - 24128

Hopefully that's all of them, but we can always have that checked later!

**Comment by MareoRaft** [comment]
That's some detective work there.  This is quite confusing.  If you click on "blacksburg" city boundary, it appears that blacksburg does not take up all of 24060.  However, the USPS zip code lookup lists *only* blacksburg for that zip code.

I guess a side question is, if a person lives in McCoy, is it okay for them to put "Blacksburg", and do they know that?

I'm going to close this since like you said we can get it checked later, after project approval and all.

Thanks so much for your help!

**Comment by nealf** [comment]
It is quite confusing. I think as far as the county is concerned for this, they just need a mailing address to send the license/tag. The USPS has their own wacky system that often doesn't line up with any real municipal boundaries, so for example, people who live outside the town limits of Blacksburg might still have "...Blacksburg VA  24060" on their mailing address. ¯\\_(ツ)_/¯
